name: 'Bump.sh'
description: 'Keep your public, private and partner API docs in sync with your code, whether you use OpenAPI or AsyncAPI.'
inputs:
  file1:
    description: 'Relative path to the first documentation file'
    required: true
    default: openapi1.json
  file2:
    description: 'Relative path to the second documentation file'
    required: true
    default: openapi2.json
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: gray-dark
  icon: book-open
